Optimizer Unit Testing
jessegrabowski/pytensor_ml pull request #10
Opened 2024-05-21 14:00 UTC by HangenYuu

## Description

Added unit testing for subsequent optimizers.

## Related Issue

- [ ] Closes
- [x] Related to #7 #8 #9

2024-05-21 14:09 UTC, HangenYuu commented
Hi @jessegrabowski, I am drafting a PR for unit testing of optimizer with optax. For PyTorch's [practice](https://github.com/pytorch/pytorch/blob/main/test/test_optim.py), they test for 2 things:
1. Functionality: The optimizer indeed makes updates to parameters that make the loss function go down. This is already confirmed for your implementations and my new ones of AdamW and Adadelta.
2. Implementation: For this one, the idea is having a case where the output is deterministic i.e, for the nth optimizing step, for input of this particular random seed, this optimizer should give this output. This one is harder, I am still experimenting with it. One thing so far is using the same input, same model with parameters all initialized to 0, PyTorch and Optax give different loss but roughly same parameters. Maybe I will use **parameters of the model at an optimizing step** for comparison.

A minor thing: Can you check and close PRs #8 and #9? I want AdamW and/or Adadelta to get merged to do testing on them too.

2024-05-21 14:28 UTC, jessegrabowski commented
We need actual unittests on #8 and #9 before we can close them. This notebook is a great starting point, we just need to figure out how to write it as a pytest test file. I can follow your start and try to give some help in the next couple days, im just super busy this week

2024-07-21 14:39 UTC, jessegrabowski commented
Sorry for letting this languish. I am getting back around to this project, will look at this ASAP.

2024-07-21 14:48 UTC, jessegrabowski requested changes
This is really great, again I'm very sorry I let this lie idle. Hope you're still keen to push it forward!

2024-07-21 14:48 UTC, jessegrabowski commented on tests/test_optimizers.py
> +    batch_slices = list(zip(cutpoints[:-1], cutpoints[1:]))
We can write a helper to generate `batch_slices`, because we're going to need it in every test

2024-07-21 14:48 UTC, jessegrabowski commented on tests/test_optimizers.py
> +model.initalize_weights()
Put this in a fixture with `scope="session"`

2024-07-21 14:48 UTC, jessegrabowski commented on tests/test_optimizers.py
> +def create_simple_model():
```suggestion
def create_mlp_classifier():
```

2024-07-21 14:48 UTC, jessegrabowski commented on tests/test_optimizers.py
> +            loss_history.append(loss)
small optimization: we only need the first and last loss, so no need to store all the intermediate values. Just compute the loss once before starting the training loop, then compare it to whatever is in the `loss` variable after the loop.

2024-07-21 14:48 UTC, jessegrabowski commented on tests/test_optimizers.py
> +    n_epochs = 10
```suggestion
    n_epochs = 1
```

This is fine if all we're doing is making sure the loss is going down

2025-01-25 16:24 UTC, merged

2025-01-25 16:24 UTC, jessegrabowski commented
Thanks for this Hang! Only 6 months from opening to merging, a new world record